# Generated by Django 4.0.4 on 2022-05-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='sub_categoria',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
