# Generated by Django 4.0.4 on 2022-05-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_proveedores_sub_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.categoria'),
        ),
    ]
