# Generated by Django 4.0.4 on 2022-05-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_proveedores_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pedidos',
            new_name='pedido',
        ),
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedore',
        ),
        migrations.RenameModel(
            old_name='ventas',
            new_name='venta',
        ),
    ]
