# Generated by Django 4.0.4 on 2022-05-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_subcategoria_alter_proveedore_sub_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedore',
            name='sub_categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='sub_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.subcategoria'),
        ),
    ]
