# Generated by Django 4.0.4 on 2022-05-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_rename_nombre_categoria_categoria_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedore',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
