# Generated by Django 4.0.4 on 2022-05-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_proveedore_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre_categoria',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='name',
            new_name='sub_categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='slug',
        ),
        migrations.AddField(
            model_name='categoria',
            name='sub_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.subcategoria'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
